//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class AreatriggerTavern
	{
		public uint Id
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}
	}
}
