//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class BattlemasterEntry
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint BgTemplate
		{
			get;
			set;
		}
	}
}
