//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class Command
	{
		public string Name
		{
			get;
			set;
		}

		public byte Security
		{
			get;
			set;
		}

		public string Help
		{
			get;
			set;
		}
	}
}
