//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class Conditions
	{
		public uint ConditionEntry
		{
			get;
			set;
		}

		public sbyte Type
		{
			get;
			set;
		}

		public uint Value1
		{
			get;
			set;
		}

		public uint Value2
		{
			get;
			set;
		}

		public uint Value3
		{
			get;
			set;
		}

		public uint Value4
		{
			get;
			set;
		}

		public byte Flags
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
