//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureModelRace
	{
		public uint Modelid
		{
			get;
			set;
		}

		public uint Racemask
		{
			get;
			set;
		}

		public uint CreatureEntry
		{
			get;
			set;
		}

		public uint ModelidRacial
		{
			get;
			set;
		}
	}
}
