//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureAiSummons
	{
		public uint Id
		{
			get;
			set;
		}

		public float PositionX
		{
			get;
			set;
		}

		public float PositionY
		{
			get;
			set;
		}

		public float PositionZ
		{
			get;
			set;
		}

		public float Orientation
		{
			get;
			set;
		}

		public uint Spawntimesecs
		{
			get;
			set;
		}

		public string Comment
		{
			get;
			set;
		}
	}
}
