//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class Creature
	{
		public uint Guid
		{
			get;
			set;
		}

		public uint Id
		{
			get;
			set;
		}

		public ushort Map
		{
			get;
			set;
		}

		public byte SpawnMask
		{
			get;
			set;
		}

		public uint Modelid
		{
			get;
			set;
		}

		public int EquipmentId
		{
			get;
			set;
		}

		public float PositionX
		{
			get;
			set;
		}

		public float PositionY
		{
			get;
			set;
		}

		public float PositionZ
		{
			get;
			set;
		}

		public float Orientation
		{
			get;
			set;
		}

		public uint Spawntimesecsmin
		{
			get;
			set;
		}

		public uint Spawntimesecsmax
		{
			get;
			set;
		}

		public float Spawndist
		{
			get;
			set;
		}

		public uint Currentwaypoint
		{
			get;
			set;
		}

		public uint Curhealth
		{
			get;
			set;
		}

		public uint Curmana
		{
			get;
			set;
		}

		public byte DeathState
		{
			get;
			set;
		}

		public byte MovementType
		{
			get;
			set;
		}
	}
}
