//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureCooldowns
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint SpellId
		{
			get;
			set;
		}

		public uint CooldownMin
		{
			get;
			set;
		}

		public uint CooldownMax
		{
			get;
			set;
		}
	}
}
