//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureSpawnData
	{
		public uint Guid
		{
			get;
			set;
		}

		public uint Id
		{
			get;
			set;
		}
	}
}
