//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureLinking
	{
		public uint Guid
		{
			get;
			set;
		}

		public uint MasterGuid
		{
			get;
			set;
		}

		public uint Flag
		{
			get;
			set;
		}
	}
}
