//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureSpawnEntry
	{
		public uint Guid
		{
			get;
			set;
		}

		public uint Entry
		{
			get;
			set;
		}
	}
}
