//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureMovementTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint PathId
		{
			get;
			set;
		}

		public uint Point
		{
			get;
			set;
		}

		public float PositionX
		{
			get;
			set;
		}

		public float PositionY
		{
			get;
			set;
		}

		public float PositionZ
		{
			get;
			set;
		}

		public float Orientation
		{
			get;
			set;
		}

		public uint Waittime
		{
			get;
			set;
		}

		public uint ScriptId
		{
			get;
			set;
		}

		public string Comment
		{
			get;
			set;
		}
	}
}
