//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureInvolvedrelation
	{
		public uint Id
		{
			get;
			set;
		}

		public uint Quest
		{
			get;
			set;
		}
	}
}
