//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureConditionalSpawn
	{
		public uint Guid
		{
			get;
			set;
		}

		public uint EntryAlliance
		{
			get;
			set;
		}

		public uint EntryHorde
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
