//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureEquipTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint Equipentry1
		{
			get;
			set;
		}

		public uint Equipentry2
		{
			get;
			set;
		}

		public uint Equipentry3
		{
			get;
			set;
		}
	}
}
