//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureSpawnDataTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public long UnitFlags
		{
			get;
			set;
		}

		public uint Faction
		{
			get;
			set;
		}

		public uint ModelId
		{
			get;
			set;
		}

		public int EquipmentId
		{
			get;
			set;
		}

		public uint CurHealth
		{
			get;
			set;
		}

		public uint CurMana
		{
			get;
			set;
		}

		public uint SpawnFlags
		{
			get;
			set;
		}
	}
}
