//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureModelInfo
	{
		public uint Modelid
		{
			get;
			set;
		}

		public float BoundingRadius
		{
			get;
			set;
		}

		public float CombatReach
		{
			get;
			set;
		}

		public float SpeedWalk
		{
			get;
			set;
		}

		public float SpeedRun
		{
			get;
			set;
		}

		public byte Gender
		{
			get;
			set;
		}

		public uint ModelidOtherGender
		{
			get;
			set;
		}

		public uint ModelidAlternative
		{
			get;
			set;
		}
	}
}
