//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureTemplateClasslevelstats
	{
		public sbyte Level
		{
			get;
			set;
		}

		public sbyte Class
		{
			get;
			set;
		}

		public uint BaseHealthExp0
		{
			get;
			set;
		}

		public uint BaseHealthExp1
		{
			get;
			set;
		}

		public uint BaseMana
		{
			get;
			set;
		}

		public float BaseDamageExp0
		{
			get;
			set;
		}

		public float BaseDamageExp1
		{
			get;
			set;
		}

		public float BaseMeleeAttackPower
		{
			get;
			set;
		}

		public float BaseRangedAttackPower
		{
			get;
			set;
		}

		public uint BaseArmor
		{
			get;
			set;
		}
	}
}
