//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class CreatureLinkingTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public ushort Map
		{
			get;
			set;
		}

		public uint MasterEntry
		{
			get;
			set;
		}

		public uint Flag
		{
			get;
			set;
		}

		public uint SearchRange
		{
			get;
			set;
		}
	}
}
