//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class DbscriptRandomTemplates
	{
		public uint Id
		{
			get;
			set;
		}

		public uint Type
		{
			get;
			set;
		}

		public int TargetId
		{
			get;
			set;
		}

		public int Chance
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
