//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class DbVersion
	{
		public string Version
		{
			get;
			set;
		}

		public string CreatureAiVersion
		{
			get;
			set;
		}

		public bool? RequiredS242501MangosCreatureSpawnTideup
		{
			get;
			set;
		}
	}
}
