//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ExplorationBasexp
	{
		public sbyte Level
		{
			get;
			set;
		}

		public int Basexp
		{
			get;
			set;
		}
	}
}
