//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class FactionStore
	{
		public uint Entry
		{
			get;
			set;
		}

		public int ReputationListID
		{
			get;
			set;
		}

		public uint BaseRepRaceMask1
		{
			get;
			set;
		}

		public uint BaseRepRaceMask2
		{
			get;
			set;
		}

		public uint BaseRepRaceMask3
		{
			get;
			set;
		}

		public uint BaseRepRaceMask4
		{
			get;
			set;
		}

		public uint BaseRepClassMask1
		{
			get;
			set;
		}

		public uint BaseRepClassMask2
		{
			get;
			set;
		}

		public uint BaseRepClassMask3
		{
			get;
			set;
		}

		public uint BaseRepClassMask4
		{
			get;
			set;
		}

		public int BaseRepValue1
		{
			get;
			set;
		}

		public int BaseRepValue2
		{
			get;
			set;
		}

		public int BaseRepValue3
		{
			get;
			set;
		}

		public int BaseRepValue4
		{
			get;
			set;
		}

		public uint ReputationFlags1
		{
			get;
			set;
		}

		public uint ReputationFlags2
		{
			get;
			set;
		}

		public uint ReputationFlags3
		{
			get;
			set;
		}

		public uint ReputationFlags4
		{
			get;
			set;
		}

		public uint Team
		{
			get;
			set;
		}

		public float SpilloverRateIn
		{
			get;
			set;
		}

		public float SpilloverRateOut
		{
			get;
			set;
		}

		public uint SpilloverMaxRankIn
		{
			get;
			set;
		}

		public uint SpilloverRankUnk
		{
			get;
			set;
		}

		public string FactionName1
		{
			get;
			set;
		}

		public string FactionName2
		{
			get;
			set;
		}

		public string FactionName3
		{
			get;
			set;
		}

		public string FactionName4
		{
			get;
			set;
		}

		public string FactionName5
		{
			get;
			set;
		}

		public string FactionName6
		{
			get;
			set;
		}

		public string FactionName7
		{
			get;
			set;
		}

		public string FactionName8
		{
			get;
			set;
		}

		public string FactionName9
		{
			get;
			set;
		}

		public string FactionName10
		{
			get;
			set;
		}

		public string FactionName11
		{
			get;
			set;
		}

		public string FactionName12
		{
			get;
			set;
		}

		public string FactionName13
		{
			get;
			set;
		}

		public string FactionName14
		{
			get;
			set;
		}

		public string FactionName15
		{
			get;
			set;
		}

		public string FactionName16
		{
			get;
			set;
		}
	}
}
