//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameEvent
	{
		public uint Entry
		{
			get;
			set;
		}

		public int ScheduleType
		{
			get;
			set;
		}

		public ulong Occurence
		{
			get;
			set;
		}

		public ulong Length
		{
			get;
			set;
		}

		public uint Holiday
		{
			get;
			set;
		}

		public uint LinkedTo
		{
			get;
			set;
		}

		public uint EventGroup
		{
			get;
			set;
		}

		public string Description
		{
			get;
			set;
		}
	}
}
