//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameEventCreature
	{
		public uint Guid
		{
			get;
			set;
		}

		public short Event
		{
			get;
			set;
		}
	}
}
