//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameEventQuest
	{
		public uint Quest
		{
			get;
			set;
		}

		public ushort Event
		{
			get;
			set;
		}
	}
}
