//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameobjectBattleground
	{
		public uint Guid
		{
			get;
			set;
		}

		public byte Event1
		{
			get;
			set;
		}

		public byte Event2
		{
			get;
			set;
		}
	}
}
