//<auto-generated>
using System;

namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameEventTime
	{
		public uint Entry
		{
			get;
			set;
		}

		public DateTime StartTime
		{
			get;
			set;
		}

		public DateTime EndTime
		{
			get;
			set;
		}
	}
}
