//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameGraveyardZone
	{
		public uint Id
		{
			get;
			set;
		}

		public uint GhostLoc
		{
			get;
			set;
		}

		public byte LinkKind
		{
			get;
			set;
		}

		public ushort Faction
		{
			get;
			set;
		}
	}
}
