//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameEventCreatureData
	{
		public uint Guid
		{
			get;
			set;
		}

		public uint EntryId
		{
			get;
			set;
		}

		public uint Modelid
		{
			get;
			set;
		}

		public uint EquipmentId
		{
			get;
			set;
		}

		public uint VendorId
		{
			get;
			set;
		}

		public uint SpellStart
		{
			get;
			set;
		}

		public uint SpellEnd
		{
			get;
			set;
		}

		public ushort Event
		{
			get;
			set;
		}
	}
}
