//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GameEventMail
	{
		public short Event
		{
			get;
			set;
		}

		public uint RaceMask
		{
			get;
			set;
		}

		public uint Quest
		{
			get;
			set;
		}

		public uint MailTemplateId
		{
			get;
			set;
		}

		public uint SenderEntry
		{
			get;
			set;
		}
	}
}
