//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class GossipMenu
	{
		public ushort Entry
		{
			get;
			set;
		}

		public uint TextId
		{
			get;
			set;
		}

		public uint ScriptId
		{
			get;
			set;
		}

		public uint ConditionId
		{
			get;
			set;
		}
	}
}
