//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class InstanceEncounters
	{
		public uint Entry
		{
			get;
			set;
		}

		public byte CreditType
		{
			get;
			set;
		}

		public uint CreditEntry
		{
			get;
			set;
		}

		public ushort LastEncounterDungeon
		{
			get;
			set;
		}
	}
}
