//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class InstanceTemplate
	{
		public ushort Map
		{
			get;
			set;
		}

		public ushort Parent
		{
			get;
			set;
		}

		public byte LevelMin
		{
			get;
			set;
		}

		public byte LevelMax
		{
			get;
			set;
		}

		public byte MaxPlayers
		{
			get;
			set;
		}

		public uint ResetDelay
		{
			get;
			set;
		}

		public string ScriptName
		{
			get;
			set;
		}

		public byte MountAllowed
		{
			get;
			set;
		}
	}
}
