//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ItemLootTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint Item
		{
			get;
			set;
		}

		public float ChanceOrQuestChance
		{
			get;
			set;
		}

		public byte Groupid
		{
			get;
			set;
		}

		public int MincountOrRef
		{
			get;
			set;
		}

		public ushort Maxcount
		{
			get;
			set;
		}

		public uint ConditionId
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
