//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ItemEnchantmentTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint Ench
		{
			get;
			set;
		}

		public float Chance
		{
			get;
			set;
		}
	}
}
