//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class LocalesGameobject
	{
		public uint Entry
		{
			get;
			set;
		}

		public string NameLoc1
		{
			get;
			set;
		}

		public string NameLoc2
		{
			get;
			set;
		}

		public string NameLoc3
		{
			get;
			set;
		}

		public string NameLoc4
		{
			get;
			set;
		}

		public string NameLoc5
		{
			get;
			set;
		}

		public string NameLoc6
		{
			get;
			set;
		}

		public string NameLoc7
		{
			get;
			set;
		}

		public string NameLoc8
		{
			get;
			set;
		}

		public string CastbarcaptionLoc1
		{
			get;
			set;
		}

		public string CastbarcaptionLoc2
		{
			get;
			set;
		}

		public string CastbarcaptionLoc3
		{
			get;
			set;
		}

		public string CastbarcaptionLoc4
		{
			get;
			set;
		}

		public string CastbarcaptionLoc5
		{
			get;
			set;
		}

		public string CastbarcaptionLoc6
		{
			get;
			set;
		}

		public string CastbarcaptionLoc7
		{
			get;
			set;
		}

		public string CastbarcaptionLoc8
		{
			get;
			set;
		}
	}
}
