//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class MailLevelReward
	{
		public byte Level
		{
			get;
			set;
		}

		public uint RaceMask
		{
			get;
			set;
		}

		public uint MailTemplateId
		{
			get;
			set;
		}

		public uint SenderEntry
		{
			get;
			set;
		}
	}
}
