//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class NpcGossip
	{
		public uint NpcGuid
		{
			get;
			set;
		}

		public uint Textid
		{
			get;
			set;
		}
	}
}
