//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class NpcVendor
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint Item
		{
			get;
			set;
		}

		public byte Maxcount
		{
			get;
			set;
		}

		public uint Incrtime
		{
			get;
			set;
		}

		public uint ExtendedCost
		{
			get;
			set;
		}

		public uint ConditionId
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
