//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PageText
	{
		public uint Entry
		{
			get;
			set;
		}

		public string Text
		{
			get;
			set;
		}

		public uint NextPage
		{
			get;
			set;
		}
	}
}
