//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PetcreateinfoSpell
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint Spell1
		{
			get;
			set;
		}

		public uint Spell2
		{
			get;
			set;
		}

		public uint Spell3
		{
			get;
			set;
		}

		public uint Spell4
		{
			get;
			set;
		}
	}
}
