//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PetFamilystats
	{
		public uint Family
		{
			get;
			set;
		}

		public float HealthModifier
		{
			get;
			set;
		}

		public float DamageModifier
		{
			get;
			set;
		}

		public float ArmorModifier
		{
			get;
			set;
		}
	}
}
