//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PetNameGeneration
	{
		public uint Id
		{
			get;
			set;
		}

		public string Word
		{
			get;
			set;
		}

		public uint Entry
		{
			get;
			set;
		}

		public sbyte Half
		{
			get;
			set;
		}
	}
}
