//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PlayercreateinfoSpell
	{
		public byte Race
		{
			get;
			set;
		}

		public byte Class
		{
			get;
			set;
		}

		public uint Spell
		{
			get;
			set;
		}

		public string Note
		{
			get;
			set;
		}
	}
}
