//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PlayerClasslevelstats
	{
		public byte Class
		{
			get;
			set;
		}

		public byte Level
		{
			get;
			set;
		}

		public ushort Basehp
		{
			get;
			set;
		}

		public ushort Basemana
		{
			get;
			set;
		}
	}
}
