//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PlayercreateinfoItem
	{
		public byte Race
		{
			get;
			set;
		}

		public byte Class
		{
			get;
			set;
		}

		public uint Itemid
		{
			get;
			set;
		}

		public byte Amount
		{
			get;
			set;
		}
	}
}
