//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PlayerXpForLevel
	{
		public uint Lvl
		{
			get;
			set;
		}

		public uint XpForNextLevel
		{
			get;
			set;
		}
	}
}
