//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PlayercreateinfoSkills
	{
		public uint RaceMask
		{
			get;
			set;
		}

		public uint ClassMask
		{
			get;
			set;
		}

		public ushort Skill
		{
			get;
			set;
		}

		public ushort Step
		{
			get;
			set;
		}

		public string Note
		{
			get;
			set;
		}
	}
}
