//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class PoolTemplate
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint MaxLimit
		{
			get;
			set;
		}

		public string Description
		{
			get;
			set;
		}
	}
}
