//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class QuestgiverGreeting
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint Type
		{
			get;
			set;
		}

		public string Text
		{
			get;
			set;
		}

		public uint EmoteId
		{
			get;
			set;
		}

		public uint EmoteDelay
		{
			get;
			set;
		}
	}
}
