//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ReferenceLootTemplateNames
	{
		public uint Entry
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}
	}
}
