//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ReputationRewardRate
	{
		public uint Faction
		{
			get;
			set;
		}

		public float QuestRate
		{
			get;
			set;
		}

		public float CreatureRate
		{
			get;
			set;
		}

		public float SpellRate
		{
			get;
			set;
		}
	}
}
