//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ScriptWaypoint
	{
		public uint Entry
		{
			get;
			set;
		}

		public uint PathId
		{
			get;
			set;
		}

		public uint Pointid
		{
			get;
			set;
		}

		public string PositionX
		{
			get;
			set;
		}

		public string PositionY
		{
			get;
			set;
		}

		public string PositionZ
		{
			get;
			set;
		}

		public float Orientation
		{
			get;
			set;
		}

		public uint Waittime
		{
			get;
			set;
		}

		public uint ScriptId
		{
			get;
			set;
		}

		public string Comment
		{
			get;
			set;
		}
	}
}
