//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ScriptedEventId
	{
		public int Id
		{
			get;
			set;
		}

		public string ScriptName
		{
			get;
			set;
		}
	}
}
