//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class ScriptedAreatrigger
	{
		public int Entry
		{
			get;
			set;
		}

		public string ScriptName
		{
			get;
			set;
		}
	}
}
