//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SkillExtraItemTemplate
	{
		public uint SpellId
		{
			get;
			set;
		}

		public uint RequiredSpecialization
		{
			get;
			set;
		}

		public float AdditionalCreateChance
		{
			get;
			set;
		}

		public byte AdditionalMaxNum
		{
			get;
			set;
		}
	}
}
