//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SkillDiscoveryTemplate
	{
		public uint SpellId
		{
			get;
			set;
		}

		public uint ReqSpell
		{
			get;
			set;
		}

		public float Chance
		{
			get;
			set;
		}
	}
}
