//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SkillFishingBaseLevel
	{
		public uint Entry
		{
			get;
			set;
		}

		public short Skill
		{
			get;
			set;
		}
	}
}
