//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpamRecords
	{
		public int Id
		{
			get;
			set;
		}

		public string Record
		{
			get;
			set;
		}
	}
}
