//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellThreat
	{
		public uint Entry
		{
			get;
			set;
		}

		public short Threat
		{
			get;
			set;
		}

		public float Multiplier
		{
			get;
			set;
		}

		public float ApBonus
		{
			get;
			set;
		}
	}
}
