//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellBonusData
	{
		public ushort Entry
		{
			get;
			set;
		}

		public float DirectBonus
		{
			get;
			set;
		}

		public float DotBonus
		{
			get;
			set;
		}

		public float ApBonus
		{
			get;
			set;
		}

		public float ApDotBonus
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
