//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellElixir
	{
		public uint Entry
		{
			get;
			set;
		}

		public byte Mask
		{
			get;
			set;
		}
	}
}
