//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellProcItemEnchant
	{
		public uint Entry
		{
			get;
			set;
		}

		public float PpmRate
		{
			get;
			set;
		}
	}
}
