//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellAffect
	{
		public ushort Entry
		{
			get;
			set;
		}

		public byte EffectId
		{
			get;
			set;
		}

		public ulong SpellFamilyMask
		{
			get;
			set;
		}
	}
}
