//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellLearnSpell
	{
		public ushort Entry
		{
			get;
			set;
		}

		public ushort SpellID
		{
			get;
			set;
		}

		public byte Active
		{
			get;
			set;
		}
	}
}
