//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellCone
	{
		public uint Id
		{
			get;
			set;
		}

		public int ConeDegrees
		{
			get;
			set;
		}
	}
}
