//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellScriptTarget
	{
		public uint Entry
		{
			get;
			set;
		}

		public byte Type
		{
			get;
			set;
		}

		public uint TargetEntry
		{
			get;
			set;
		}

		public uint InverseEffectMask
		{
			get;
			set;
		}
	}
}
