//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellFacing
	{
		public uint Entry
		{
			get;
			set;
		}

		public bool Facingcasterflag
		{
			get;
			set;
		}
	}
}
