//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellPetAuras
	{
		public uint Spell
		{
			get;
			set;
		}

		public uint Pet
		{
			get;
			set;
		}

		public uint Aura
		{
			get;
			set;
		}
	}
}
