//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellTargetPosition
	{
		public uint Id
		{
			get;
			set;
		}

		public ushort TargetMap
		{
			get;
			set;
		}

		public float TargetPositionX
		{
			get;
			set;
		}

		public float TargetPositionY
		{
			get;
			set;
		}

		public float TargetPositionZ
		{
			get;
			set;
		}

		public float TargetOrientation
		{
			get;
			set;
		}
	}
}
