//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class SpellChain
	{
		public int SpellId
		{
			get;
			set;
		}

		public int PrevSpell
		{
			get;
			set;
		}

		public int FirstSpell
		{
			get;
			set;
		}

		public sbyte Rank
		{
			get;
			set;
		}

		public int ReqSpell
		{
			get;
			set;
		}
	}
}
