//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class TaxiShortcuts
	{
		public uint Pathid
		{
			get;
			set;
		}

		public uint Takeoff
		{
			get;
			set;
		}

		public uint Landing
		{
			get;
			set;
		}

		public string Comments
		{
			get;
			set;
		}
	}
}
