//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class TrainerGreeting
	{
		public uint Entry
		{
			get;
			set;
		}

		public string Text
		{
			get;
			set;
		}
	}
}
