//<auto-generated>
namespace ValhallaLootList.ItemImporter.WarcraftDatabase
{
	public class WorldTemplate
	{
		public ushort Map
		{
			get;
			set;
		}

		public string ScriptName
		{
			get;
			set;
		}
	}
}
